version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install tox
      - run: tox

  test_pypi_publish:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install build twine
      - run: python -m build

  pypi_publish:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install build twine
      - run: python -m build

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - test_pypi_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - pypi_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /(\d)+(\.(\d)+)+/

